/**
 * View API
 * View API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ServerRequestType = 'ACTION' | 'WIDGET_ACTION' | 'CREATE_VIEW_CONTEXT' | 'UPDATE_VIEW_CONTEXT' | 'GET_VIEW_CONTEXT' | 'HANDLE_MESSAGE_RESULT' | 'SHOW_SMARTLINK' | 'DOWNLOAD' | 'GET_COMPONENT_MODEL';

export const ServerRequestType = {
    Action: 'ACTION' as ServerRequestType,
    WidgetAction: 'WIDGET_ACTION' as ServerRequestType,
    CreateViewContext: 'CREATE_VIEW_CONTEXT' as ServerRequestType,
    UpdateViewContext: 'UPDATE_VIEW_CONTEXT' as ServerRequestType,
    GetViewContext: 'GET_VIEW_CONTEXT' as ServerRequestType,
    HandleMessageResult: 'HANDLE_MESSAGE_RESULT' as ServerRequestType,
    ShowSmartlink: 'SHOW_SMARTLINK' as ServerRequestType,
    Download: 'DOWNLOAD' as ServerRequestType,
    GetComponentModel: 'GET_COMPONENT_MODEL' as ServerRequestType
};

