/**
 * View API
 * View API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerRequestType } from './serverRequestType';
import { UiActionRequest } from './uiActionRequest';


/**
 * The server request track is an object encapsulates the UiRequest and other parameters of the perform actions. It stands for normal and widget actions also. 
 */
export interface ServerRequestTrack { 
    /**
     * The name of the view the request is performed on.
     */
    viewName: string;
    /**
     * The UUID of the view the request is performed on.
     */
    viewUuid: string;
    /**
     * The identifier of the widget if it is a widget action perform.
     */
    widgetId?: string;
    /**
     * The identifier of the widget node if it is a widget action perform.
     */
    nodeId?: string;
    /**
     * The start of the service.
     */
    startTime: string;
    /**
     * The end of the service.
     */
    endTime?: string;
    /**
     * The number of executed reads.
     */
    readCount?: number;
    /**
     * The summarized execution time of the reads.
     */
    readTime?: number;
    /**
     * The number of executed writes.
     */
    writeCount?: number;
    /**
     * The summarized execution time of the writes.
     */
    writeTime?: number;
    request: UiActionRequest;
    type: ServerRequestType;
}

