/**
 * View API
 * View API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@it4all.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The generic execution statistic is an object for the actuator infrastructure. It could be initiated for many purposes and contains the count, the minimum, average and maximum execution times. 
 */
export interface StatisticRecord { 
    /**
     * The minimum execution time of the given action in millisec.
     */
    min?: number;
    /**
     * The average execution time of the given action in millisec.
     */
    avg?: number;
    /**
     * The average execution time of the given action in millisec.
     */
    max?: number;
    /**
     * The number of executed requests.
     */
    counter?: number;
    /**
     * The summarized execution time of the request.
     */
    sum?: number;
}

